### ISSUE TITLE
TypeError: takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by McClatcheyM** [jeremymcrae/fitDNM#2]
Novice (non) Python user with limited departmental support. Apologies in advance.  

I'm trying to apply this fitDNM (Python version) to a preliminary dataset of WGS-derived DNMs (100,000 genomes project [UK])

fitDNM cloned and locally installed on CentOS Linux 7;  Python 3.7.4

Input:
- standard input with locally imported mutation rates and regional constraint (via gnomAD/ExAC) metrics
- CADD scores are locally hosted, bgzipped and indexed
- provisionally run as an interactive job on a LSF cluster

_python scripts/run_fitDNM.py \
  --males 89 \
  --females 89 \
  --de-novos input/de_novos.tsv \
  --genome-build GRCh38 \
  --severity PATH_TO_LOCAL_CADD_SNV \
  --rates PATH_TO_LOCAL_MUT_RATES \
  --constraint PATH_TO_LOCAL_REGIONAL_CONSTRAINT \
  --output output/output.txt_

Error output:
![image](https://user-images.githubusercontent.com/52492434/138880246-6a3d3341-d25b-4f31-ac54-e88d05c6225f.png)

As shown, recurring issue with "TypeError : [] takes 2 positional arguments but 3 were given"
This error relates to Line 47 but I'm anticipating the same error from lines 53 and 54 on the same logic.
 
I understand that this can be overcome by addition of **self** in the definition but am unsure how to overcome this with the list of arguments that are being defined in the function. Apologies again for the naivety. Please let me know if this is more likely to be a local issue which I can try and address.

Any advice would be appreciated regardless. Thanks

**Comment by jeremymcrae** [comment]
Sorry about that! I had changed something in a package that fitDNM depends on, and had forgotten to update fitDNM to match. I've fixed this now, and it shouldn't give the same problem. 

I also changed things so that installing this now should make a `fitdnm` command available, e.g. 

```sh
fitdnm \
  --males 156 \
  --females 108 \
  --de-novos examples/de_novos.txt \
  --severity CADD_SNV_PATH \
  --output examples/output.txt
```

Simplified a bit on my end, but I hope that doesn't cause much trouble for you! Let me know if it is, and I can put a `run_fitDNM.py` script back in.

**Comment by McClatcheyM** [comment]
Hi Jeremy,
Many thanks  for your time on this. It's very much appreciated. 
FYI I wasn't able to execute the `pip install . ` due to local environment restrictions in the Genomics England remote research environment platform that I'm using. I therefore had to re-install using the previous setup command which appeared to still work.

I'm subsequently able to run using the `fitdnm` command without any obvious issues

Unfortunately I'm returning a further pandas error with "KeyError : 'chrom'" - see appended screenshot
I don't think this is due to my denovos input (tab-separated input) as the columns appear distinct.
Likewise, I've tried with and without using my local paths for `--rates` and `--constraint` with the same errors returning regardless of whether they are specified or not.

![image](https://user-images.githubusercontent.com/52492434/139074078-d039a64f-38d4-478a-9a9a-c2a9056a33c3.png)

Any further input would be very much appreciated. Apologies again if I'm missing something obvious.

**Comment by jeremymcrae** [comment]
Sorry for the delayed response! I fixed the KeyError: 'chrom' error, that happens in the GEL environment due to the locked down network access - it cannot retrieve gene coordinates and sequence from Ensembl. I've added two more options to instead provide gene coordinates and sequence via local files. Download, install and try this updated command (I dropped the regional constraint option, since that wasn't adding much here):

```bash
fitdnm \
  --males 156 \
  --females 108 \
  --de-novos examples/de_novos.txt \
  --gencode $GENCODE_GTF_PATH \
  --fasta $GENOME_FASTA \
  --severity $CADD_SNV_PATH \
  --output examples/output.txt
```

 - `--gencode`: Gencode annotations GTF e.g. for [GRCh37](http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_38/GRCh37_mapping/gencode.v38lift37.annotation.gtf.gz), or for [GRCh38](http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_38/gencode.v38.annotation.gtf.gz). You'll need to match the build your de novo mutations are on. 
- `--fasta`: Genome sequence fasta file. Again, match the genome build.

Hopefully that's straightforward for what you need to include?

It took me a bit longer than just fixing that problem, since I wanted to avoid any other problems as well, so ran my test dataset through, and fixed a few minor bugs, including some more obscure deeper ones that affected specific genes. I can now run fitDNM against the example de novos file, and reproduce earlier results (well, not exact values, but with a high correlation, at least).

Hope that helps, and let me know if it still fails to work for you!

**Comment by McClatcheyM** [comment]
Hi Jeremy, 

Thanks for your updated reply and appologies for the delay in acknoweldging it. 
I've been trying to work with the local caches in the GEL environment as suggested, which appears to be working for the gencode and fasta inputs.

The bug/issue I'm having still appears to be with the CADD dataset.
It's stored in the GEL environment in the default gzipped version (standard downloaded version) but my understanding is that your version of `fitDNM` currently requires to read it as a bgzipped input. I'm getting a continuous `ValueError` derived from the `bgzf.py` script.*

![image](https://user-images.githubusercontent.com/52492434/141297136-0e7f3dfa-467e-41d9-ac8f-f3075520f31d.png) *

In the GEL research environment I've tried to get around this by copying the default CADD download anonotation to a scratch space, have decompressed it and (re-)compressed it with bgzip. *The appended debugging traceback was generated from running on the supposedly bgzipped CADD input.  

I'm wondering if this step is really necessary, as most repositories carry the base .gzipped CADD annotation?

**Comment by jeremymcrae** [comment]
I'd prefer to use the bgzipped version, since this allows indexing the file, so you can quickly retrieve CADD scores for arbitrary genome regions. Otherwise we'd have to read through the full CADD file to find the scores for the genes of interest. Which could be done, but it would add ~40 minutes of processing upfront (as opposed to milliseconds for loading from indexed file). 

I'd prefer to figure out why your file gave errors before changing the code to read the full file. Your error is a bit puzzling, I'd expect errors reading bgzipped files to come through a different module, pysam, rather than Bio.bgzf. Can you give the full error lines, not just the last few lines?

I assume your bgzipping went something like this?
```sh
# compress with bgzip
zcat whole_genome_SNVs.tsv.gz | bgzip > whole_genome_SNVs.tsv.bgz

# index the CADD file with tabix
tabix -s 1 -b 2 -e 2 whole_genome_SNVs.tsv.bgz
```

I checked this worked with the first 1000 lines e.g.
```sh
zcat whole_genome_SNVs.tsv.gz | head -n 1000 | bgzip > bgzipped.tsv.gz
tabix -s 1 -b 2 -e 2 bgzipped.tsv.gz
```

then you should be able to fetch regions e.g. `tabix bgzipped.tsv.gz 1:10100-10110`. Can you confirm that works for you on your bgzipped/indexed CADD file?

**Comment by McClatcheyM** [comment]
Hi again Jeremy
Thanks for your last response and apologies for the delay in replying. I was having some issues with the stability of the GEL environment to work through the debugging steps.

I've managed to bgzip and re-index the CADD file as above as you'd suggested and it appears to have worked also.
I've subsequently tried to submit the `fitdnm` process again and got a similar standard error traceback:
 
![image](https://user-images.githubusercontent.com/52492434/142042281-4bad4703-9dba-42d7-aae5-886e066924d5.png)

I'm not experienced in reading this python traceback but am wondering if this is an issue with reading the local GENCODE file
Thanks again for any input and advice you may be able to offer. Apologies for causing you this additional hassle.

**Comment by jeremymcrae** [comment]
hmm, try uncompressing your genome fasta file, and run again with the uncompressed fasta, that might do it?

**Comment by McClatcheyM** [comment]
Thanks for this. I think things are working now.

FYI: I had been trying to use tried the reference genome held locally in GEL as 
`GCA_000001405.15_GRCh38_no_alt_analysis_set.fna`  but didn't have adequate permissions to handle the indexed file.

![image](https://user-images.githubusercontent.com/52492434/142047893-9dde0246-cbf1-40fe-9219-d19678cbc8a3.png)

I've subsequently used a `GRCh38Decoy_no_alt.fa` which is also available locally. 
This appears to have different permissions assigned. 
`fitdnm` appears to be working fine in terms of the actual analysis. 

It seems I've got some ongoing issues (I was aware of that already) with submitting batch jobs to GEL but that's not your problem so I'll have to get that addressed. Hopefully I can get that resolved and get some output now.

Thanks so much for your assistance.
